api-version: 1.8

name: PowerRush
version: 1.0
authors: [Enlaniel,Falkunai]
main: fr.teamkiwi.powerrush.Main
description: Plugin super cool

commands :
  config :
    description : Ouvre le menu de configuration
    permission : powerrush.config
    permission-message : Vous n'êtes pas administrateur !
    aliases: [config, cfg, configs]
  start :
    description : Lance la partie
    permission : powerrush.start
    permission-message : Vous n'êtes pas administrateur !
  forcestop :
    description : Arrete la partie
    permission : powerrush.forcestop
    permission-message : Vous n'êtes pas administrateur !
  saveinventory :
    description : Configure l'inventaire de départ
    permission : powerrush.saveinv
    permission-message : Vous n'êtes pas administrateur !
    aliases: [saveinv, saveinventory]
  showinventory :
    description : Permet de voir l'inventaire de départ
    permission : powerrush.showinv
    permission-message : Si vous voyez ce message, veuillez prevenir la TeamKiwi !
    aliases: [showinv, showinventory]
  powerrushhelp:
    description : Donne toutes les commandes du plugin et leurs utilitées
    permission : powerrush.powerrushhelp
    permission-message : Si vous voyez ce message, veuillez prevenir la TeamKiwi !
    aliases: [prhelp, powerrushhelp]
  selectkit :
    description : Commande de debug permettant de choisir un kit
    permission : powerrush.debug.selectkit
    permission-message : Vous n'êtes pas administrateur !
    aliases: [selectkit, debugselectkit]
  showyml :
    description : Montre le fichier config.yml
    permission : powerrush.debug.showyml
    permission-message : Vous n'êtes pas administrateur !
    aliases: [showyml, debugshowyml]
  joingame:
    description: Permet de creer une team et de la rejoindre
    permission: powerrush.debug.joingame
    permission-message: Vous n'êtes pas administrateur !
    aliases: [ joingame, debugjoingame ]
  initserver :
    description : Commande permettant d'init le config.yml
    permission : powerrush.initserver
    permission-message : Vous n'êtes pas administrateur !
  
permissions :
  powerrush.debug.*:
    default: op
  powerrush.config:
    default: op
  powerrush.start:
    default: op
  powerrush.forcestop:
    default: op
  powerrush.saveinv:
    default: op
  powerrush.initserver:
    default: op
  powerrush.powerrushhelp:
    default: true
  powerrush.showinv:
    default: true